//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDataServiceLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentList
    {
        public int DocumentId { get; set; }
        public string Title { get; set; }
        public bool CanBeLent { get; set; }
        public int MaxDaysRent { get; set; }
        public string TypeCode { get; set; }
    }
}
