//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDataServiceLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentProperty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentProperty()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public int TypeId { get; set; }
        public int LanguageId { get; set; }
        public bool CanBeLent { get; set; }
        public int MaxDaysRent { get; set; }
        public int FinePrice { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual DocumentType DocumentTypes { get; set; }
        public virtual Language Languages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
    }
}
